share_todo/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('favicon.ico', RedirectView.as_view(url=r'static/favicon.ico')),
    path('', include('todo.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

todo/urls.py
from django.conf.urls import url
from django.urls import include, path
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'todo'

urlpatterns = [
    path('todo/', login_required(views.TodoListView.as_view()), name='todo-list'),
    path('done/', login_required(views.DoneListView.as_view()), name='done-list'),
    path('todo/<int:pk>', login_required(views.TodoDetailView.as_view()), name='todo-detail'),
    path('', views.IndexView.as_view(), name='index'),
    path('alt/<int:pk>', views.alt, name='alt'),
    path('calendar/', login_required(views.CalendarView.as_view()), name='calendar'),
    path('api/event', views.event),
]

todo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Todo(models.Model):
    time_add = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=64)
    detail = models.TextField(blank=True)
    deadline = models.DateTimeField(blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    done = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def seconds_left(self):
        return (self.deadline - timezone.now()).total_seconds()

    def state(self):
        if self.done:
            return 'Done'
        elif self.seconds_left() > 0:
            return 'Todo'
        else:
            return 'Exceeded'

    class Meta:
        ordering = ['deadline']

todo/views.py
from django.shortcuts import render, redirect, get_object_or_404, resolve_url
from django.views import generic
from .models import *
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
import json
from django.utils.datetime_safe import datetime
import time


class TodoListView(generic.ListView):
    template_name = 'todo/list.html'
    context_object_name = 'todos'

    def get_queryset(self):
        if self.request.GET.get('all'):
            return Todo.objects.filter(done=False)
        else:
            return Todo.objects.filter(done=False, user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['todo'] = True
        return context


class DoneListView(generic.ListView):
    template_name = 'todo/list.html'
    context_object_name = 'todos'

    def get_queryset(self):
        if self.request.GET.get('all'):
            return Todo.objects.filter(done=True)
        else:
            return Todo.objects.filter(done=True, user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['todo'] = False
        return context


class TodoDetailView(generic.DetailView):
    template_name = 'todo/detail.html'
    model = Todo
    context_object_name = 'todo'


class CalendarView(generic.View):
    def get(self, request):
        return render(request, 'todo/calendar.html', locals())


class IndexView(generic.View):
    def get(self, request):
        return redirect('todo:todo-list')


@login_required
def alt(request, pk):
    todo = get_object_or_404(Todo, pk=pk)
    todo.done = not todo.done
    todo.save()
    return redirect('todo:todo-list') if todo.done else redirect('todo:done-list')


@login_required
def event(request):
    events = []
    if request.GET.get('start') and request.GET.get('end'):
        fr = request.GET.get('start')
        if 'T' not in fr:
            fr += 'T0:0:0'
        fr = datetime.strptime(fr, '%Y-%m-%dT%H:%M:%S')
        to = request.GET.get('end')
        if 'T' not in to:
            to += 'T0:0:0'
        to = datetime.strptime(to, '%Y-%m-%dT%H:%M:%S')
        todos = Todo.objects.filter(deadline__range=[fr, to])
    else:
        todos = Todo.objects.all()
    for todo in todos:
        ddl_str = todo.deadline.strftime('%Y-%m-%dT%H:%M:%S')
        events.append({
            'title': todo.title,
            'start': ddl_str,
            'end': ddl_str,
            'color': '#eee' if todo.done else '#6cf' if todo.user == request.user else '#cdf',

            'textColor': '#bbb' if todo.done else '#000',
            'url': resolve_url('todo:todo-detail', todo.pk),
            'detail': todo.detail,
        })
    return HttpResponse(json.dumps(events))

templates/base.html
<!DOCTYPE html>
<html lang="en-US">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Todo{% endblock %}</title>
    <link rel="icon" href="/favicon.ico" type="image/x-icon" />
    <!-- Bootstrap -->
    <link href="https://cdn.bootcss.com/twitter-bootstrap/4.2.1/css/bootstrap.min.css" rel="stylesheet" />
    <!-- Font Awesome -->
    <link href="https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://cdn.bootcss.com/webui-popover/2.1.15/jquery.webui-popover.min.css" rel="stylesheet">
    <link href="https://cdn.bootcss.com/tooltipster/3.3.0/css/tooltipster.min.css" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block css %}{% endblock %}
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-3" id="site_header">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <a class="navbar-brand" href="/">
                Share Todo
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    {% block navbar %}
                    <li class="nav-item">
                        <a href="{% url 'admin:todo_todo_add' %}" class="nav-link">
                            Add
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'todo:todo-list' %}" class="nav-link">
                            Todo
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'todo:done-list' %}" class="nav-link">
                            Done
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'todo:calendar' %}" class="nav-link">
                            Calendar
                        </a>
                    </li>
                    {% endblock %}
                </ul>
            <div class="dropdown-divider"></div>
                <ul class="navbar-nav mr-right">
                    <li>
                        <a class="nav-link" href="https://github.com/zyayoung/share-todo" target="_blank">
                            <i class="fa fa-github fa-lg"></i>
                            <span class="d-lg-none">Github</span>
                        </a>
                    </li>
                    <div class="dropdown-divider"></div>
                    <li class="nav-item d-none d-lg-block">
                        <a class="nav-link">
                            |
                        </a>
                    </li>
                    {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <i class="fa fa-user fa-lg" aria-hidden="true"></i>
                            {{ request.user.username }}
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}?next=/">
                            <i class="fa fa-sign-out fa-lg" aria-hidden="true"></i>
                            Sign out
                        </a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">
                            <i class="fa fa-sign-in fa-lg" aria-hidden="true"></i>
                            Sign In
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <i class="fa fa-user-plus" aria-hidden="true"></i>
                            Sign Up
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>

    <div class="container">
        {% block content %}{% endblock %}
    </div>
    <script>
    var True = true;
    var False = false;
    </script>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
    <!-- Bootstrap Select -->
    <script src="https://cdn.bootcss.com/popper.js/1.14.6/umd/popper.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://cdn.bootcss.com/twitter-bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap-select/1.13.5/js/bootstrap-select.min.js"></script>
    <script src="https://cdn.bootcss.com/echarts/4.2.0-rc.2/echarts.min.js"></script>
    <script src="https://cdn.bootcss.com/webui-popover/2.1.15/jquery.webui-popover.min.js"></script>
    <script src="https://cdn.bootcss.com/tooltipster/3.3.0/js/jquery.tooltipster.min.js"></script>
    {% block script %}{% endblock %}
</body>

</html>

templates/todo/calendar.html
{% extends 'base.html' %}
{% block css %}
<link href="https://cdn.bootcss.com/fullcalendar/3.10.0/fullcalendar.min.css" rel="stylesheet">
{#<link href="https://cdn.bootcss.com/fullcalendar/3.10.0/fullcalendar.print.min.css" rel="stylesheet">#}
{% endblock %}
{% block content %}
<div id="calendar"></div>
{% endblock %}
{% block script %}
<script src="https://cdn.bootcss.com/moment.js/2.24.0/moment.min.js"></script>
<script src="https://cdn.bootcss.com/fullcalendar/3.10.0/fullcalendar.min.js"></script>
<script type="text/javascript">
$('#calendar').fullCalendar({
    header: {
        left: 'prev,next',
        center: 'title',
        right: 'month,basicWeek'
    },
    titleFormat: 'MMM YY',
    defaultView: 'month',
    contentHeight: Math.max(480, document.documentElement.clientHeight - 160),
    {#eventLimit: true,#}
    nowIndicator: true,
    eventRender: function(eventObj, $el) {
        if (eventObj.detail){
            $el.popover({
                title: eventObj.title,
                content: eventObj.detail,
                trigger: 'hover',
                placement: 'top',
            });
        }
    },
    dayClick: function(date, jsEvent, view) {
        today = new Date();
        today -= 3600000 * 24;
        if (date >= today){
            window.location = "{% url 'admin:todo_todo_add' %}?date="+date.format();
        }
    },
    eventSources: [
        {
          url: '/api/event',
        }
    ],
    timeFormat: document.documentElement.clientWidth>414?'H':' ',
    windowResize: function(view) {
        $('#calendar').fullCalendar('option', 'timeFormat', document.documentElement.clientWidth>414?'H':' ');
        $('#calendar').fullCalendar('option', 'contentHeight', Math.max(480, document.documentElement.clientHeight - 160));
    }
});
</script>
{% endblock %}

templates/todo/detail.html
{% extends 'base.html' %}
{% block title %}Todo{% endblock %}
{% block content %}
    <table class="table">
    <tr>
        <th>Title</th>
        <td>{{ todo.title }}</td>
    </tr>
    <tr>
        <th>Detail</th>
        <td>{{ todo.detail }}</td>
    </tr>
    <tr>
        <th>Deadline</th>
        <td>{{ todo.deadline }}</td>
    </tr>
    </tr>
    <tr>
        <th>User</th>
        <td>{{ todo.user }}</td>
    </tr>
    <tr>
        <th>State</th>
        <td>{{ todo.state }}</td>
    </tr>
    <tr>
        <th>Time Left</th>
        <td class="seconds_left">
            {{ todo.seconds_left }}
        </td>
    </tr>
    </table>
    <a href="{% url 'admin:todo_todo_change' todo.pk %}?next={{ request.path }}" class="btn btn-outline-primary">
        <i class="fa fa-edit"></i> Edit
    </a>
{% endblock %}
{% block script %}
<script>
var secondsLeft = $(".seconds_left");
for(var i=0; i<secondsLeft.length; i++){
    let seconds = secondsLeft[i].innerHTML * 1000;
    let passed = false;
    if(seconds < 0){
        passed = true;
        seconds = -seconds;
    }
    let time = new Date(seconds);
    secondsLeft[i].innerHTML = (passed?'- ':'') + Math.floor(seconds/(1000*3600*24)) + " days " + time.getUTCHours()+':'+time.getUTCMinutes()+':'+time.getUTCSeconds();
    if(!{{ todo.done }}){
        if(passed){
            secondsLeft[i].classList.add('text-danger');
        }
        else if (seconds < 3600 * 1000){
            secondsLeft[i].classList.add('text-warning');
        }
    }
}
</script>
{% endblock %}

templates/todo/list.html
{% extends 'base.html' %}
{% block title %}Todo{% endblock %}
{% block css %}
{% endblock %}
{% block content %}
    <table class="table table-sm">
    <thead>
    <th></th>
    <th>Title</th>
    <th>Time Left</th>
    {% if request.GET.all %}
    <th>User</th>
    {% endif %}
    </thead>
    <tbody>
    {% for todo in todos %}
        <tr>
        <td>
            <a href="{% url 'todo:alt' todo.pk %}">
                {% if todo.done %}
                <i class="fa fa-check-square-o"></i>
                {% else %}
                <i class="fa fa-square-o"></i>
                {% endif %}
            </a>
        </td>
        <td>
            <a href="{% url 'todo:todo-detail' todo.pk %}">
                {% if todo.detail %}
                <span class="tooltipster" title="{{ todo.detail }}">{{ todo }}</span>
                {% else %}
                {{ todo }}
                {% endif %}
            </a>
        </td>
        <td class="seconds_left">
            {{ todo.seconds_left }}
        </td>
        {% if request.GET.all %}
        <td>
            {{ todo.user }}
        </td>
        {% endif %}
        </tr>
    {% endfor %}
    </tbody>
    </table>
    {% if todo %}
    <a href="{% url 'admin:todo_todo_add' %}" class="btn btn-outline-primary">
        <i class="fa fa-plus"></i> Add
    </a>
    {% endif %}
    {% if not request.GET.all %}
    <a href="{{ request.path }}?all=True" class="btn btn-outline-primary">
        <i class="fa fa-eye"></i> All
    </a>
    {% else %}
    <a href="{{ request.path }}" class="btn btn-outline-primary">
        <i class="fa fa-eye-slash"></i> Hide
    </a>
    {% endif %}
{% endblock %}
{% block script %}
<script>
    $(document).ready(function() {
        $('.tooltipster').tooltipster();
    });
</script>
<script>
var secondsLeft = $(".seconds_left");
for(var i=0; i<secondsLeft.length; i++){
    let seconds = secondsLeft[i].innerHTML * 1000;
    let passed = false;
    if(seconds < 0){
        passed = true;
        seconds = -seconds;
    }
    let time = new Date(seconds);
    secondsLeft[i].innerHTML = (passed?'- ':'') + Math.floor(seconds/(1000*3600*24)) + "d " + time.getUTCHours()+'h';
    if(!{{ todos.0.done }}){
        if(passed){
            secondsLeft[i].classList.add('text-danger');
        }
        else if (seconds < 3600 * 1000){
            secondsLeft[i].classList.add('text-warning');
        }
    }
}
</script>
{% endblock %}